version: "3"

services:
 # for orexi restaurant service:
  restaurantservice:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    command: node restaurant.js
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3040|| exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5

  # for login service:
  loginservice:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node login.js
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000|| exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
